package jlc.exceptionHandling;
public class Lab545 {
	public static void main(String[] args) {
		System.out.println("Main Started");
		try {
			String data = args[0];
			int x = Integer.parseInt(data);
			int res = 10/x;
			System.out.println("Result: "+res);
		}catch(Exception e) {
			e.getClass()
			System.out.println("*Enter correct value ");
		}
		System.out.println("Main completed");
	}
}
